import { Inter } from "next/font/google";
import "./globals.css";
import Indicator from "@/components/scroll/scrollindacator";
import CustomBackground from "@/components/gridBackground/custom_background";
import Nav from "@/components/nav/nav";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<CustomBackground />
				<Indicator />
				<Nav />
				{children}
				<Footer />
			</body>
		</html>
	);
}
